const test = require('node:test')
const assert = require('node:assert/strict')
const {
  syncStenciUser,
  buildUserSyncLockKey,
  UserSyncError,
  databaseDiagnostic,
} = require('../services/stenciUserService')
const StenciMapper = require('../../integrations/stenci/StenciMapper')

class MemoryPool {
  constructor({ users = [], people = [] } = {}) { this.users=structuredClone(users); this.people=structuredClone(people); this.nextUser=Math.max(0,...this.users.map(x=>x.id))+1; this.nextPerson=Math.max(0,...this.people.map(x=>x.id))+1; this.tail=Promise.resolve() }
  async getConnection() { const p=this; let unlock, held=false
    return { beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){}, async query(sql,v=[]){ const q=sql.replace(/\s+/g,' ').trim()
      if(q.startsWith('SELECT GET_LOCK')) { if(held) return [[{acquired:1}]]; const prior=p.tail; p.tail=new Promise(r=>{unlock=r}); await prior; held=true; return [[{acquired:1}]] }
      if(q.startsWith('SELECT RELEASE_LOCK')) { if(held){ held=false; unlock?.() }; return [[{released:1}]] }
      if(q.includes('WHERE u.stenci_user_id =')) return [[p.users.find(u=>u.stenci_user_id===v[0])].filter(Boolean)]
      if(q.includes('FROM people p LEFT JOIN users') && q.includes('WHERE p.cpf =')) { const person=p.people.find(x=>x.cpf===v[0]); if(!person)return [[]]; const linked=p.users.filter(u=>u.person_id===person.id); return [[...(linked.length?linked:[null])].map(u=>({...person,linked_user_id:u?.id,linked_stenci_user_id:u?.stenci_user_id}))] }
      if(q.includes('FROM people p LEFT JOIN users') && q.includes('WHERE p.email =')) { const person=p.people.find(x=>x.email===v[0]); if(!person)return [[]]; const linked=p.users.filter(u=>u.person_id===person.id); return [[...(linked.length?linked:[null])].map(u=>({...person,linked_user_id:u?.id,linked_stenci_user_id:u?.stenci_user_id}))] }
      if(q.includes('WHERE p.email =')) return [[p.users.find(u=>p.people.find(x=>x.id===u.person_id)?.email===v[0])].filter(Boolean)]
      if(q.includes('u.username = ? OR u.stenci_username')) return [[p.users.find(u=>u.username===v[0]||u.stenci_username===v[1])].filter(Boolean)]
      if(q.includes('WHERE p.cpf =')) return [[p.users.find(u=>p.people.find(x=>x.id===u.person_id)?.cpf===v[0])].filter(Boolean)]
      if(q.startsWith('INSERT INTO people')) { const id=p.nextPerson++; p.people.push({id,cpf:v[0],full_name:v[1],email:v[2]}); return [{insertId:id}] }
      if(q.startsWith('UPDATE people SET')) { const x=p.people.find(x=>x.id===v.at(-1)); let i=0; for(const c of ['full_name','email','cpf']) if(q.includes(`${c} = ?`)) x[c]=v[i++]; return [{affectedRows:1}] }
      if(q.startsWith('UPDATE users SET')) { const u=p.users.find(x=>x.id===v[4]); Object.assign(u,{stenci_user_id:v[0],stenci_username:v[1],username:v[2],person_id:v[3],status:'active'}); return [{affectedRows:1}] }
      if(q.startsWith('INSERT INTO users')) { const id=p.nextUser++; p.users.push({id,username:v[0],password:null,person_id:v[1],status:'active',role:'user',stenci_user_id:v[2],stenci_username:v[3]}); return [{insertId:id}] }
      if(q.startsWith('SELECT u.id, u.username')) { const u=p.users.find(x=>x.id===v[0]), x=p.people.find(x=>x.id===u.person_id); return [[{...u,full_name:x?.full_name,email:x?.email,avatar_url:x?.avatar_url}]] }
      throw new Error(`Unsupported SQL: ${q}`)
    }}
  }
}
const identity=(x={})=>({stenci_user_id:'stenci-1',stenci_username:'05286020984',identity:'05286020984',name:'Maria Atual',email:'maria@example.test',...x})
const legacy=(x={})=>new MemoryPool({people:[{id:4,full_name:'Antigo',email:x.email??'maria@example.test',cpf:x.cpf===undefined?'05286020984':x.cpf}],users:[{id:7,username:x.username||'legacy',password:'hash',person_id:4,role:'admin',status:'active',stenci_user_id:x.stenci??null,stenci_username:null}]})

test('creates a new passwordless user and never persists supplied password or token',async()=>{const p=new MemoryPool(), input={...identity(),password:'secret',token:'jwt'}; await syncStenciUser(p,input); assert.equal(p.users.length,1); assert.equal(p.users[0].password,null); assert.equal(p.users[0].token,undefined); assert.notEqual(p.users[0].password,input.password)})
test('updates a user found by stenci_user_id without creating one',async()=>{const p=legacy({stenci:'stenci-1'}); const u=await syncStenciUser(p,identity()); assert.equal(u.id,7); assert.equal(p.users.length,1); assert.equal(p.people[0].full_name,'Maria Atual')})
test('links an existing user by email when stenci_user_id is null',async()=>{const p=legacy({username:'old',cpf:null}); const u=await syncStenciUser(p,identity({identity:null})); assert.equal(u.id,7); assert.equal(p.users.length,1); assert.equal(p.users[0].stenci_user_id,'stenci-1')})
test('links by username/CPF and preserves its leading zero and string type',async()=>{const p=legacy({username:'05286020984',email:'old@example.test'}); await syncStenciUser(p,identity({email:'new@example.test'})); assert.equal(p.users[0].stenci_user_id,'stenci-1'); assert.equal(p.users[0].username,'05286020984'); assert.equal(typeof p.people[0].cpf,'string')})
test('same email with another stenci_user_id returns identity conflict',async()=>{const p=legacy({stenci:'other'}); await assert.rejects(syncStenciUser(p,identity()),e=>e instanceof UserSyncError&&e.code==='USER_IDENTITY_CONFLICT'&&e.status===409); assert.equal(p.users[0].stenci_user_id,'other')})
test('repeated and simultaneous synchronization create one user',async()=>{const p=new MemoryPool(); await syncStenciUser(p,identity()); await syncStenciUser(p,identity()); assert.equal(p.users.length,1); const c=new MemoryPool(); const users=await Promise.all([syncStenciUser(c,identity()),syncStenciUser(c,identity())]); assert.equal(c.users.length,1); assert.deepEqual(users.map(x=>x.id),[1,1])})
test('builds a short, deterministic and opaque lock name from stenci_user_id',()=>{const personal='user@example.test-05286020984-Maria'; const first=buildUserSyncLockKey(personal); assert.equal(first.length,36); assert.ok(first.length<=64); assert.equal(first,buildUserSyncLockKey(personal)); assert.notEqual(first,buildUserSyncLockKey('another-user')); assert.doesNotMatch(first,/user|example|05286020984|Maria/i)})
test('GET_LOCK and RELEASE_LOCK receive exactly the same key',async()=>{const calls=[]; const p=new MemoryPool(); const connection=await p.getConnection(); const original=connection.query.bind(connection); connection.query=async(sql,values)=>{if(/GET_LOCK|RELEASE_LOCK/.test(sql))calls.push({sql,lockName:values[0]}); return original(sql,values)}; p.getConnection=async()=>connection; await syncStenciUser(p,identity()); assert.equal(calls.length,2); assert.match(calls[0].sql,/GET_LOCK/); assert.match(calls[1].sql,/RELEASE_LOCK/); assert.equal(calls[0].lockName,calls[1].lockName)})
test('an error during synchronization still releases the acquired lock',async()=>{const calls=[]; const connection={query:async(sql,values)=>{if(sql.includes('GET_LOCK'))return [[{acquired:1}]]; if(sql.includes('RELEASE_LOCK')){calls.push(values[0]); return [[{released:1}]]} throw new Error('sync failed')},beginTransaction:async()=>{},rollback:async()=>{},release(){}}; await assert.rejects(syncStenciUser({getConnection:async()=>connection},identity()),{code:'REALMED_USER_SYNC_FAILED'}); assert.deepEqual(calls,[buildUserSyncLockKey('stenci-1')])})
test('lock timeout and lock errors return controlled codes without attempting release',async()=>{for(const [result,code] of [[0,'USER_SYNC_LOCK_TIMEOUT'],[null,'USER_SYNC_LOCK_ERROR']]){let releases=0; const connection={query:async(sql)=>{if(sql.includes('GET_LOCK'))return [[{acquired:result}]]; if(sql.includes('RELEASE_LOCK'))releases++; return [[]]},release(){}}; await assert.rejects(syncStenciUser({getConnection:async()=>connection},identity()),error=>error instanceof UserSyncError&&error.code===code); assert.equal(releases,0)}})
test('reuses an unlinked person found by CPF instead of inserting a duplicate',async()=>{const p=new MemoryPool({people:[{id:9,cpf:'05286020984',email:'old@example.test',full_name:'Old'}]}); const u=await syncStenciUser(p,identity()); assert.equal(u.person_id,9); assert.equal(p.people.length,1)})
test('reuses an unlinked person found by email instead of inserting a duplicate',async()=>{const p=new MemoryPool({people:[{id:9,cpf:null,email:'maria@example.test',full_name:'Old'}]}); const u=await syncStenciUser(p,identity({identity:null})); assert.equal(u.person_id,9); assert.equal(p.people.length,1)})
test('a Stenci-linked user is safely rebound to its unique matching legacy person',async()=>{const p=legacy({stenci:'stenci-1',email:'old@example.test',cpf:null}); p.people.push({id:9,cpf:'05286020984',email:'maria@example.test',full_name:'Matching'}); const u=await syncStenciUser(p,identity()); assert.equal(u.id,7); assert.equal(u.person_id,9); assert.equal(p.people.length,2)})
test('different people matching CPF and email are an identity conflict',async()=>{const p=new MemoryPool({people:[{id:1,cpf:'05286020984',email:'first@example.test'},{id:2,cpf:'other',email:'maria@example.test'}]}); await assert.rejects(syncStenciUser(p,identity()),{code:'USER_IDENTITY_CONFLICT'}); assert.equal(p.users.length,0)})
test('duplicate diagnostics retain index metadata but discard duplicate data',()=>{const d=databaseDiagnostic({code:'ER_DUP_ENTRY',errno:1062,sqlState:'23000',sqlMessage:"Duplicate entry 'private@example.test' for key 'people.uk_people_email'"}); assert.deepEqual(d,{code:'ER_DUP_ENTRY',errno:1062,constraint:'people.uk_people_email',duplicateField:'people.uk_people_email',sqlState:'23000'}); assert.doesNotMatch(JSON.stringify(d),/private@example\.test/)})
test('unexpected database errors are always logged safely and retained as the cause',async()=>{const original=Object.assign(new Error('private SQL value'),{code:'ER_DUP_ENTRY',errno:1062,sqlState:'23000',sqlMessage:"Duplicate entry 'private@example.test' for key 'people.uk_people_email'",sql:'UPDATE people SET email = private@example.test'}); const entries=[]; const pool={getConnection:async()=>({query:async()=>{throw original},rollback:async()=>{},release(){}})}; await assert.rejects(syncStenciUser(pool,identity(),{logger:{info(){},error:(...args)=>entries.push(args)}}),error=>error.code==='REALMED_USER_SYNC_FAILED'&&error.cause===original); const output=JSON.stringify(entries); assert.match(output,/ER_DUP_ENTRY|uk_people_email/); assert.doesNotMatch(output,/private@example\.test|UPDATE people/)})
test('mapper uses user.id as the primary Stenci key and keeps CPF textual',()=>{const mapped=StenciMapper.userIdentity({user:{id:'user-9',identityId:'identity-legacy',name:'Maria',identity:{type:'cpf',value:'05286020984'}}},'fallback'); assert.equal(mapped.stenci_user_id,'user-9'); assert.equal(mapped.stenci_username,'05286020984'); assert.equal(mapped.identity,'05286020984'); assert.equal(typeof mapped.identity,'string')})
