const express = require('express')
const knexFactory = require('knex')
const knexConfig = require('../knexfile')
const auth = require('../middleware/auth')
const { modulePermission } = require('../middleware/permission')

const knex = knexFactory(knexConfig[process.env.NODE_ENV || 'development'] || knexConfig.development)
const router = express.Router()
const clean = (v) => typeof v === 'string' ? v.trim() : v
const id = (v) => { const n = Number(v); if (!Number.isInteger(n) || n < 1) throw Object.assign(new Error('Identificador inválido.'), { status: 400 }); return n }
const handle = (res, error) => { console.error('[Central de Guias]', error); res.status(error.status || 500).json({ error: error.status ? error.message : 'Erro interno da Central de Guias.' }) }
const required = (body, fields) => { for (const field of fields) if (body[field] === undefined || clean(body[field]) === '') throw Object.assign(new Error(`Campo obrigatório: ${field}.`), { status: 400 }) }

router.use(auth)

const catalogs = {
  'insurance-providers': { table: 'insurance_providers', module: 'insurance_providers', required: ['name', 'authorization_type'], fields: ['name','internal_code','ans_registration','authorization_type','active','notes'], logo: true },
  professionals: { table: 'professionals', module: 'professionals', required: ['full_name','type','council','council_number','state'], fields: ['full_name','type','council','council_number','state','cbo','active','notes'] },
  procedures: { table: 'procedures', module: 'procedures', required: ['code','description','type'], fields: ['code','description','table_name','type','active','notes'] },
}
for (const [path, config] of Object.entries(catalogs)) {
  router.get(`/${path}`, modulePermission(config.module), async (req, res) => { try { const q = knex(`${config.table} as catalog`).select('catalog.*').orderBy(`catalog.${config.fields[0]}`); if(config.logo)q.select(knex.raw("EXISTS(SELECT 1 FROM insurance_provider_assets asset WHERE asset.insurance_provider_id = catalog.id AND asset.asset_type = 'LOGO' AND asset.active = 1) AS has_logo"));if (req.query.active !== undefined) q.where('catalog.active', req.query.active === 'true'); res.json(await q) } catch (e) { handle(res, e) } })
  router.post(`/${path}`, modulePermission(config.module, 'create'), async (req, res) => { try { required(req.body, config.required); const data = Object.fromEntries(config.fields.filter((f) => req.body[f] !== undefined).map((f) => [f, clean(req.body[f])])); const [created] = await knex(config.table).insert(data); res.status(201).json(await knex(config.table).where({ id: created }).first()) } catch (e) { handle(res, e) } })
  router.put(`/${path}/:id`, modulePermission(config.module, 'edit'), async (req, res) => { try { const itemId = id(req.params.id); const data = Object.fromEntries(config.fields.filter((f) => req.body[f] !== undefined).map((f) => [f, clean(req.body[f])])); await knex(config.table).where({ id: itemId }).update(data); const row = await knex(config.table).where({ id: itemId }).first(); if (!row) throw Object.assign(new Error('Cadastro não encontrado.'), { status: 404 }); res.json(row) } catch (e) { handle(res, e) } })
  router.patch(`/${path}/:id/active`, modulePermission(config.module, 'edit'), async (req, res) => { try { const itemId = id(req.params.id); await knex(config.table).where({ id: itemId }).update({ active: Boolean(req.body.active) }); res.json(await knex(config.table).where({ id: itemId }).first()) } catch (e) { handle(res, e) } })
}

router.get('/patients', modulePermission('patients'), async (req, res) => { try { const q = knex('patients').orderBy('full_name'); if (clean(req.query.search)) q.where('full_name', 'like', `%${clean(req.query.search)}%`); res.json(await q) } catch (e) { handle(res, e) } })
router.post('/patients', modulePermission('patients', 'create'), async (req, res) => { try { required(req.body, ['full_name']); const data = pick(req.body, ['external_source','external_id','full_name','cpf','birth_date','phone','email']); const [patientId] = await knex('patients').insert(data); res.status(201).json(await knex('patients').where({ id: patientId }).first()) } catch (e) { duplicate(e); handle(res, e) } })
router.put('/patients/:id', modulePermission('patients', 'edit'), async (req, res) => { try { const patientId = id(req.params.id); await knex('patients').where({ id: patientId }).update(pick(req.body, ['external_source','external_id','full_name','cpf','birth_date','phone','email'])); res.json(await knex('patients').where({ id: patientId }).first()) } catch (e) { duplicate(e); handle(res, e) } })
router.post('/patients/:id/insurances', modulePermission('patients', 'edit'), async (req, res) => { try { required(req.body, ['insurance_provider_id','card_number']); const data = { ...pick(req.body, ['insurance_provider_id','card_number','card_expiration','plan','holder','active']), patient_id: id(req.params.id) }; const [rowId] = await knex('patient_insurances').insert(data); res.status(201).json(await knex('patient_insurances').where({ id: rowId }).first()) } catch (e) { handle(res, e) } })
router.get('/patients/:id', modulePermission('patients'), async (req, res) => { try { const patientId = id(req.params.id); const patient = await knex('patients').where({ id: patientId }).first(); if (!patient) throw Object.assign(new Error('Paciente não encontrado.'), { status: 404 }); patient.insurances = await knex('patient_insurances as pi').join('insurance_providers as ip','ip.id','pi.insurance_provider_id').where('pi.patient_id',patientId).select('pi.*','ip.name as insurance_name'); patient.processes = await processQuery().where('gp.patient_id',patientId); res.json(patient) } catch (e) { handle(res, e) } })

function processQuery() { return knex('guide_processes as gp').join('patients as p','p.id','gp.patient_id').join('patient_insurances as pi','pi.id','gp.patient_insurance_id').join('insurance_providers as ip','ip.id','pi.insurance_provider_id').join('professionals as ph','ph.id','gp.physiotherapist_id').leftJoin('professionals as dr','dr.id','gp.requesting_doctor_id').select('gp.*','p.full_name as patient_name','ip.name as insurance_name','ip.id as insurance_provider_id','ph.full_name as physiotherapist_name','dr.full_name as doctor_name') }
router.get('/guide-processes', modulePermission('guide_processes'), async (req, res) => { try {
  const page = Math.max(1,Number(req.query.page)||1), pageSize = Math.min(100,Math.max(1,Number(req.query.pageSize)||20)); const q = processQuery()
  const filters = ['physiotherapist_id','requesting_doctor_id','document_status','treatment_status','billing_status','priority']
  filters.forEach((f) => { if (req.query[f] !== undefined && req.query[f] !== '') q.where(`gp.${f}`,req.query[f]) })
  if (req.query.authorization_status) q.whereIn('gp.authorization_status',String(req.query.authorization_status).split(',').filter(Boolean))
  if (req.query.insurance_provider_id) q.where('pi.insurance_provider_id',req.query.insurance_provider_id)
  if (clean(req.query.search)) q.where('p.full_name','like',`%${clean(req.query.search)}%`)
  for (const [parameter, column, operator] of [['assessment_date_from','assessment_date','>='],['assessment_date_to','assessment_date','<='],['expected_start_date_from','expected_start_date','>='],['expected_start_date_to','expected_start_date','<=']]) if (req.query[parameter]) q.where(`gp.${column}`,operator,req.query[parameter])
  const countQuery = q.clone().clearSelect().clearOrder().countDistinct('gp.id as total').first()
  const sorts = { start_asc:[['expected_start_date','asc'],['priority','desc'],['created_at','asc']], start_desc:[['expected_start_date','desc']], assessment_desc:[['assessment_date','desc']], assessment_asc:[['assessment_date','asc']], priority_desc:[['priority','desc'],['expected_start_date','asc']], created_asc:[['created_at','asc']], created_desc:[['created_at','desc']] }
  for (const [column,direction] of (sorts[req.query.sort] || sorts.start_asc)) q.orderBy(`gp.${column}`,direction)
  const data = await q.limit(pageSize).offset((page-1)*pageSize); const total = Number((await countQuery).total); res.json({ data, pagination: { page, pageSize, total, pages: Math.ceil(total/pageSize) } })
} catch (e) { handle(res, e) } })
router.post('/guide-processes', modulePermission('guide_processes','create'), async (req, res) => { const trx = await knex.transaction(); try { required(req.body,['patient_id','patient_insurance_id','physiotherapist_id','assessment_date','expected_start_date','requested_sessions']); validateSessions(req.body); const data = { ...pick(req.body, processFields), created_by: req.user.id }; const [processId] = await trx('guide_processes').insert(data); await history(trx,processId,req.user.id,'PROCESS_CREATED',null,null,null); await trx.commit(); res.status(201).json(await processQuery().where('gp.id',processId).first()) } catch (e) { await trx.rollback(); handle(res,e) } })
router.get('/guide-processes/:id', modulePermission('guide_processes'), async (req,res) => { try { const processId=id(req.params.id); const process=await processQuery().where('gp.id',processId).first(); if(!process) throw Object.assign(new Error('Processo não encontrado.'),{status:404}); process.documents=await documents(processId); process.authorizations=await knex('guide_authorizations').where({guide_process_id:processId}).orderBy('created_at','desc'); process.procedures=await knex('guide_process_procedures as gpp').join('procedures as pr','pr.id','gpp.procedure_id').where('gpp.guide_process_id',processId).select('gpp.*','pr.code','pr.description','pr.type'); process.pendingItems=await knex('guide_process_pending_items').where({guide_process_id:processId}).orderBy('created_at','desc'); process.history=await knex('guide_process_history as h').leftJoin('users as u','u.id','h.user_id').leftJoin('people as pe','pe.id','u.person_id').where('h.guide_process_id',processId).select('h.*','pe.full_name as user_name').orderBy('h.created_at','desc'); res.json(process) } catch(e){handle(res,e)} })
router.put('/guide-processes/:id', modulePermission('guide_processes','edit'), async (req,res) => { const trx=await knex.transaction(); try { const processId=id(req.params.id), old=await trx('guide_processes').where({id:processId}).first(); if(!old) throw Object.assign(new Error('Processo não encontrado.'),{status:404}); const data=pick(req.body,processFields); validateSessions({...old,...data}); if(data.authorization_status==='READY' && old.document_status!=='COMPLETE') throw Object.assign(new Error('Complete os documentos obrigatórios antes de liberar para autorização.'),{status:422}); await trx('guide_processes').where({id:processId}).update(data); for(const field of Object.keys(data)) if(String(old[field]??'')!==String(data[field]??'')) await history(trx,processId,req.user.id,field.endsWith('_status')?'STATUS_CHANGED':'FIELD_CHANGED',field,old[field],data[field]); await trx.commit(); res.json(await processQuery().where('gp.id',processId).first()) } catch(e){await trx.rollback();handle(res,e)} })

function validateSessions(data, authorizationType) {
  for (const field of ['requested_sessions','authorized_sessions','performed_sessions']) if (data[field] != null && (!Number.isInteger(Number(data[field])) || Number(data[field]) < 0)) throw Object.assign(new Error(`${field} deve ser um inteiro maior ou igual a zero.`), {status:422})
  if (authorizationType !== 'SESSION_TOKEN' && data.authorized_sessions != null && Number(data.performed_sessions || 0) > Number(data.authorized_sessions)) throw Object.assign(new Error('Sessões realizadas não podem ultrapassar as autorizadas.'), {status:422})
}

const processFields=['patient_id','patient_insurance_id','physiotherapist_id','requesting_doctor_id','assessment_date','expected_start_date','requested_sessions','authorized_sessions','performed_sessions','priority','notes','external_source','external_reference','treatment_status','billing_status']
function pick(body, fields) { return Object.fromEntries(fields.filter((f)=>body[f]!==undefined).map((f)=>[f,clean(body[f]) || null])) }
function duplicate(e) { if (e.code === 'ER_DUP_ENTRY') { e.status=409; e.message='Já existe um registro com estes identificadores.' } }
async function history(db, processId, userId, action, field, oldValue, newValue, metadata) { await db('guide_process_history').insert({guide_process_id:processId,user_id:userId,action,field,old_value:oldValue==null?null:String(oldValue),new_value:newValue==null?null:String(newValue),metadata:metadata?JSON.stringify(metadata):null}) }
async function documents(processId) { return knex('guide_process_documents as d').leftJoin('users as u','u.id','d.uploaded_by').leftJoin('people as p','p.id','u.person_id').where('d.guide_process_id',processId).whereNull('d.deleted_at').select('d.id','d.document_type','d.original_name','d.mime_type','d.file_size','d.source','d.created_at','p.full_name as uploaded_by_name').orderBy('d.created_at','desc') }

module.exports = { router, knex, history, handle, id, documents, validateSessions }
