<template>
  <PageShell title="Novo Tratamento" subtitle="Prepare o tratamento e a documentação recebida antes de encaminhá-lo ao faturamento">
    <form class="space-y-5" @submit.prevent="save">
      <section class="panel"><h2 class="section-title">1. Paciente</h2><label class="field">PACIENTE<input v-model="search" class="input" placeholder="Buscar paciente no Stenci..." @input="findPatients"></label><p v-if="searching" class="mt-2 text-sm text-gray-500">Consultando o Stenci...</p><div v-if="searchError" class="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ searchError }}</div><div v-if="patients.length" class="mt-2 divide-y rounded-xl border"><button v-for="patient in patients" :key="patient.external_id" type="button" class="block w-full p-3 text-left hover:bg-gray-50" :disabled="importing" @click="selectPatient(patient)"><span class="flex items-center gap-2"><b>{{ patient.full_name }}</b><span class="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-bold text-blue-700">STENCI</span></span><span class="mt-1 block text-sm text-gray-600">CPF: {{ patient.cpf || '—' }} · Nascimento: {{ date(patient.birth_date) }} · Telefone: {{ patient.phone || '—' }}</span><span v-if="patient.insurance" class="mt-1 block text-sm text-gray-600">{{ patient.insurance.name || 'Convênio não informado' }}<template v-if="patient.insurance.plan"> · {{ patient.insurance.plan }}</template><template v-if="patient.insurance.card_number"><br>Carteirinha: {{ patient.insurance.card_number }}</template></span></button><button v-if="hasMore" type="button" class="block w-full p-3 text-center font-semibold text-blue-700 hover:bg-gray-50" :disabled="searching" @click="loadMore">Carregar mais</button></div><p v-if="importing" class="mt-3 font-semibold text-blue-700">Importando dados do Stenci...</p><div v-if="selectedPatient" class="mt-4 rounded-xl bg-blue-50 p-4"><span class="flex items-center gap-2"><b>Paciente selecionado: {{ selectedPatient.full_name }}</b><span class="rounded-full px-2 py-0.5 text-xs font-bold" :class="selectedPatient.external_source === 'STENCI' ? 'bg-blue-100 text-blue-700' : 'bg-gray-200 text-gray-700'">{{ selectedPatient.external_source === 'STENCI' ? 'STENCI' : 'MANUAL' }}</span></span><p class="mt-1 text-sm text-gray-600">CPF: {{ selectedPatient.cpf || '—' }} · Nascimento: {{ date(selectedPatient.birth_date) }} · Telefone: {{ selectedPatient.phone || '—' }}</p><p v-if="selectedInsurance" class="mt-1 text-sm text-gray-600">Convênio: {{ selectedInsurance.insurance_name || '—' }} · Plano: {{ selectedInsurance.plan || '—' }} · Carteirinha: {{ selectedInsurance.card_number || '—' }} · Validade: {{ date(selectedInsurance.card_expiration) }}</p><RouterLink class="link mt-2 inline-block" :to="`/pacientes/${selectedPatient.id}`">Confirmar ou atualizar cadastro</RouterLink></div><RouterLink class="btn-secondary mt-3 inline-block" to="/pacientes">Paciente não encontrado? Cadastrar manualmente</RouterLink></section>

      <section class="panel"><h2 class="section-title">2. Dados do tratamento</h2><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label class="field">Convênio<select v-model="form.patient_insurance_id" class="input" required><option value="">Selecione</option><option v-for="item in insurances" :key="item.id" :value="item.id">{{ item.insurance_name }} · {{ item.card_number }} · {{ item.plan || 'Plano não informado' }}</option></select></label><label class="field">Fisioterapeuta responsável<select v-model="form.physiotherapist_id" class="input" required><option value="">Selecione</option><option v-for="item in physiotherapists" :key="item.id" :value="item.id">{{ item.full_name }}</option></select></label><label class="field">Médico solicitante<select v-model="form.requesting_doctor_id" class="input"><option value="">Selecione</option><option v-for="item in doctors" :key="item.id" :value="item.id">{{ item.full_name }}</option></select></label><label class="field">Data da avaliação<input v-model="form.assessment_date" type="date" class="input" required></label><label class="field">Data prevista de início<input v-model="form.expected_start_date" type="date" class="input" required></label><label class="field">Quantidade de sessões<input v-model.number="form.requested_sessions" type="number" min="1" class="input" required></label><label class="field md:col-span-2 xl:col-span-3">Observações<textarea v-model="form.notes" class="input min-h-20"></textarea></label></div></section>

      <section class="panel"><h2 class="section-title">3. Dias de tratamento</h2><div class="flex flex-wrap gap-2"><label v-for="day in weekdays" :key="day.value" class="rounded-xl border px-4 py-3"><input v-model="form.treatment_days" type="checkbox" :value="day.value" class="mr-2">{{ day.label }}</label></div><label class="field mt-4 max-w-md">Período / horário preferencial<input v-model="form.preferred_period" class="input" placeholder="Ex.: Manhã, 14h ou após as 18h"></label></section>

      <section class="panel"><h2 class="section-title">4. Procedimentos</h2><p class="mb-4 text-sm text-gray-500">Selecione no cadastro de procedimentos; nenhum código é fixado nesta tela.</p><div class="grid gap-4 md:grid-cols-3"><label v-for="kind in procedureKinds" :key="kind.type" class="field">{{ kind.label }}<select v-model="procedureSelection[kind.type].procedure_id" class="input"><option value="">Selecione</option><option v-for="item in procedures.filter(p => p.type === kind.type)" :key="item.id" :value="item.id">{{ item.code }} · {{ item.description }}</option></select><input v-model.number="procedureSelection[kind.type].requested_quantity" class="input mt-2" type="number" min="1" :placeholder="kind.type === 'CONSULTATION' ? '1' : 'Quantidade'"></label></div></section>

      <section class="panel"><h2 class="section-title">5. Documentação recebida</h2><div class="grid gap-4 md:grid-cols-2"><article v-for="card in documentCards" :key="card.type" class="rounded-xl border p-4"><h3 class="font-bold">{{ card.label }}</h3><p class="my-2 text-sm text-gray-500">{{ files[card.type]?.name || card.empty }}</p><label class="btn-secondary inline-block">Anexar<input type="file" class="hidden" accept=".pdf,.jpg,.jpeg,.png" @change="chooseFile($event, card.type)"></label><div v-if="card.usability && files[card.type]" class="mt-3 flex gap-4 text-sm"><label><input v-model="usability[card.type]" type="radio" :value="true"> Adequado</label><label><input v-model="usability[card.type]" type="radio" :value="false"> Necessita ajuste</label></div></article><article class="rounded-xl border p-4"><h3 class="font-bold">Outros documentos</h3><p class="my-2 text-sm text-gray-500">Encaminhamentos, relatórios, exames e complementos.</p><label class="btn-secondary inline-block">Selecionar arquivos<input type="file" multiple class="hidden" accept=".pdf,.jpg,.jpeg,.png" @change="chooseOthers"></label><p v-for="file in otherFiles" :key="file.name" class="mt-2 text-sm">{{ file.name }}</p></article></div></section>

      <section class="panel"><h2 class="section-title">6. Documentação necessária</h2><p class="text-sm text-gray-600">Guias ausentes ou marcadas como “Necessita ajuste” poderão ser geradas com os modelos já cadastrados após salvar. O original permanecerá disponível ao lado do documento preparado pela Realmed.</p></section>
      <section class="panel"><h2 class="section-title">7. Resumo / conclusão</h2><ul class="space-y-2 text-sm"><li v-for="item in checklist" :key="item.label" :class="item.ok ? 'text-success-700' : 'text-error-700'">{{ item.ok ? '✓' : '✕' }} {{ item.label }}</li></ul><p class="mt-4 font-semibold">{{ locallyComplete ? 'Documentação pronta para conferência' : 'Documentação incompleta' }}</p><button class="btn mt-4 px-6 py-3" :disabled="saving">{{ locallyComplete ? 'Finalizar preparação' : 'Salvar com documentação pendente' }}</button></section>
    </form>
  </PageShell>
</template>
<script setup lang="ts">
/* eslint-disable @typescript-eslint/no-explicit-any */
import { computed, onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import api from '@/plugins/axios'
import PageShell from '@/components/PageShell.vue'
const router=useRouter(),search=ref(''),patients=ref<any[]>([]),selectedPatient=ref<any>(),insurances=ref<any[]>([]),professionals=ref<any[]>([]),procedures=ref<any[]>([]),files=reactive<Record<string,File|undefined>>({}),otherFiles=ref<File[]>([]),usability=reactive<Record<string,boolean>>({}),saving=ref(false),searching=ref(false),importing=ref(false),searchError=ref(''),hasMore=ref(false),offset=ref(0)
const form=reactive<any>({patient_insurance_id:'',physiotherapist_id:'',requesting_doctor_id:'',assessment_date:'',expected_start_date:'',requested_sessions:10,notes:'',treatment_days:[],preferred_period:''})
const weekdays=[['MONDAY','Segunda'],['TUESDAY','Terça'],['WEDNESDAY','Quarta'],['THURSDAY','Quinta'],['FRIDAY','Sexta'],['SATURDAY','Sábado']].map(([value,label])=>({value,label}))
const procedureKinds=[{type:'PHYSIOTHERAPY',label:'Fisioterapia'},{type:'ELECTROSTIMULATION',label:'Eletroestimulação'},{type:'CONSULTATION',label:'Consulta / Avaliação'}]
const procedureSelection=reactive<Record<string,any>>(Object.fromEntries(procedureKinds.map(k=>[k.type,{procedure_id:'',requested_quantity:k.type==='CONSULTATION'?1:10}])))
const documentCards=[{type:'PHYSIOTHERAPY_GUIDE',label:'Guia de Fisioterapia',empty:'Nenhuma guia recebida',usability:true},{type:'CONSULTATION_GUIDE',label:'Guia de Consulta / Avaliação',empty:'Nenhuma guia recebida',usability:true},{type:'PHYSIO_ASSESSMENT',label:'Avaliação Fisioterapêutica',empty:'Anexe o formulário preenchido',usability:false}]
const physiotherapists=computed(()=>professionals.value.filter(p=>p.type==='PHYSIOTHERAPIST')),doctors=computed(()=>professionals.value.filter(p=>p.type==='DOCTOR'))
const checklist=computed(()=>[{label:'Avaliação fisioterapêutica',ok:!!files.PHYSIO_ASSESSMENT},{label:'Guia de consulta adequada',ok:!!files.CONSULTATION_GUIDE&&usability.CONSULTATION_GUIDE===true},{label:'Guia de fisioterapia adequada',ok:!!files.PHYSIOTHERAPY_GUIDE&&usability.PHYSIOTHERAPY_GUIDE===true},{label:'Eletroestimulação incluída',ok:!!procedureSelection.ELECTROSTIMULATION.procedure_id}]),locallyComplete=computed(()=>checklist.value.every(i=>i.ok))
let timer:number|undefined
function findPatients(){window.clearTimeout(timer);searchError.value='';offset.value=0;if(search.value.trim().length<2){patients.value=[];hasMore.value=false;return}timer=window.setTimeout(()=>fetchPatients(false),300)}
async function fetchPatients(append:boolean){searching.value=true;try{const response=(await api.get('/integrations/stenci/patients/search',{params:{search:search.value.trim(),limit:30,offset:offset.value}})).data;patients.value=append?[...patients.value,...response.items]:response.items;hasMore.value=response.hasMore}catch{if(!append)patients.value=[];hasMore.value=false;searchError.value='Não foi possível consultar o Stenci no momento.'}finally{searching.value=false}}
async function loadMore(){offset.value+=30;await fetchPatients(true)}
async function selectPatient(patient:any){importing.value=true;searchError.value='';try{const synced=(await api.post(`/integrations/stenci/patients/${encodeURIComponent(patient.external_id)}/sync`,{patient:patient.raw})).data;selectedPatient.value=(await api.get(`/patients/${synced.patient.id}`)).data;insurances.value=selectedPatient.value.insurances.filter((i:any)=>i.active);form.patient_insurance_id=synced.patient_insurance?.id||'';patients.value=[];hasMore.value=false;search.value=selectedPatient.value.full_name}catch{searchError.value='Não foi possível importar o paciente do Stenci. Você ainda pode cadastrá-lo manualmente.'}finally{importing.value=false}}
function chooseFile(event:Event,type:string){files[type]=(event.target as HTMLInputElement).files?.[0]}
function chooseOthers(event:Event){otherFiles.value=Array.from((event.target as HTMLInputElement).files||[])}
async function upload(processId:number,type:string,file:File){await api.post(`/guide-processes/${processId}/documents`,file,{params:{documentType:type,isUsable:type==='PHYSIO_ASSESSMENT'?true:usability[type]},headers:{'Content-Type':file.type,'X-File-Name':encodeURIComponent(file.name)}})}
async function save(){if(!selectedPatient.value)return window.alert('Selecione um paciente.');saving.value=true;try{const proceduresPayload=Object.values(procedureSelection).filter((p:any)=>p.procedure_id);const treatment=(await api.post('/guide-processes',{...form,patient_id:selectedPatient.value.id,procedures:proceduresPayload})).data;for(const card of documentCards){const file=files[card.type];if(file)await upload(treatment.id,card.type,file)}for(const file of otherFiles.value)await upload(treatment.id,'OTHER',file);await router.push(`/central-de-guias/tratamentos/${treatment.id}`)}finally{saving.value=false}}
const date=(value:string)=>value?new Date(`${String(value).slice(0,10)}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const selectedInsurance=computed(()=>insurances.value.find((item:any)=>String(item.id)===String(form.patient_insurance_id)))
onMounted(async()=>{[professionals.value,procedures.value]=await Promise.all([(await api.get('/professionals',{params:{active:true}})).data,(await api.get('/procedures',{params:{active:true}})).data])})
</script>
<style scoped>.field{display:flex;flex-direction:column;gap:.4rem;font-size:.8rem;font-weight:600;color:#475467}.field .input{width:100%;font-weight:400;color:#344054}</style>
