exports.up = async function up(knex) {
  await knex.schema.createTable('contratos', (table) => {
    table.increments('id').primary()
    table.string('titulo').notNullable()
    table.string('tipo').nullable()
    table.string('contratado').nullable()
    table.string('contratante').nullable()
    table.decimal('valor_mensal', 15, 2).defaultTo(0)
    table.decimal('valor_total', 15, 2).defaultTo(0)
    table.date('data_inicio').nullable()
    table.date('data_vencimento').nullable()
    table.string('recorrencia').nullable()
    table.string('indice_reajuste').nullable()
    table.string('status').defaultTo('Rascunho')
    table.string('responsavel_interno').nullable()
    table.text('observacoes').nullable()
    table.json('anexos').nullable()
    table.json('workflow').nullable()
    table.timestamps(true, true)
    table.timestamp('deleted_at').nullable()
  })

  await knex.schema.createTable('contrato_aditivos', (table) => {
    table.increments('id').primary()
    table
      .integer('contrato_id')
      .unsigned()
      .references('id')
      .inTable('contratos')
      .onDelete('CASCADE')
    table.string('tipo_aditivo').nullable()
    table.decimal('novo_valor', 15, 2).nullable()
    table.date('novo_prazo').nullable()
    table.text('justificativa').nullable()
    table.string('arquivo_pdf').nullable()
    table.date('data').nullable()
    table.string('status').defaultTo('Rascunho')
    table.timestamps(true, true)
    table.timestamp('deleted_at').nullable()
  })

  await knex.schema.createTable('contrato_negociacoes', (table) => {
    table.increments('id').primary()
    table
      .integer('contrato_id')
      .unsigned()
      .references('id')
      .inTable('contratos')
      .onDelete('CASCADE')
    table.decimal('valor_atual', 15, 2).nullable()
    table.decimal('valor_proposto', 15, 2).nullable()
    table.decimal('percentual_reajuste', 6, 2).nullable()
    table.string('status').defaultTo('Em andamento')
    table.date('data_proposta').nullable()
    table.text('anotacoes').nullable()
    table.json('anexos').nullable()
    table.json('historico').nullable()
    table.timestamps(true, true)
    table.timestamp('deleted_at').nullable()
  })

  await knex.schema.createTable('contrato_templates', (table) => {
    table.increments('id').primary()
    table.string('nome_do_template').notNullable()
    table.string('tipo').nullable()
    table.text('conteudo_html', 'longtext').nullable()
    table.string('arquivo_pdf').nullable()
    table.timestamps(true, true)
    table.timestamp('deleted_at').nullable()
  })

  await knex.schema.createTable('contrato_alertas', (table) => {
    table.increments('id').primary()
    table
      .integer('contrato_id')
      .unsigned()
      .references('id')
      .inTable('contratos')
      .onDelete('CASCADE')
    table.string('tipo_alerta').notNullable()
    table.integer('dias_antecedencia').nullable()
    table.boolean('enviar_no_vencimento').defaultTo(false)
    table.json('destinatarios').nullable()
    table.boolean('enviar_email').defaultTo(true)
    table.boolean('enviar_notificacao').defaultTo(true)
    table.timestamps(true, true)
    table.timestamp('deleted_at').nullable()
  })

  await knex.schema.createTable('contrato_logs', (table) => {
    table.increments('id').primary()
    table
      .integer('contrato_id')
      .unsigned()
      .references('id')
      .inTable('contratos')
      .onDelete('CASCADE')
    table.string('acao').notNullable()
    table.text('descricao').nullable()
    table.timestamp('created_at').defaultTo(knex.fn.now())
    table.timestamp('updated_at').nullable()
    table.timestamp('deleted_at').nullable()
  })
}

exports.down = async function down(knex) {
  await knex.schema.dropTableIfExists('contrato_logs')
  await knex.schema.dropTableIfExists('contrato_alertas')
  await knex.schema.dropTableIfExists('contrato_templates')
  await knex.schema.dropTableIfExists('contrato_negociacoes')
  await knex.schema.dropTableIfExists('contrato_aditivos')
  await knex.schema.dropTableIfExists('contratos')
}
