const createTableIfMissing = async (knex, tableName, tableCallback) => {
  const exists = await knex.schema.hasTable(tableName)
  if (!exists) {
    await knex.schema.createTable(tableName, tableCallback)
  }
}

exports.up = async (knex) => {
  await createTableIfMissing(knex, 'not_inc_incidentes', (table) => {
    table.increments('id').primary()
    table.string('nm_criador', 60)
    table.string('ds_setor', 60).notNullable()
    table.string('ds_fato', 1000).notNullable()
    table.string('ds_conseq', 60).notNullable()
    table.string('ds_acao', 1000).notNullable()
    table.string('ds_conseq_det', 1000).notNullable()
    table.dateTime('dt_incidente').notNullable()
    table.string('ds_maquina', 400)
    table.string('status', 30).defaultTo('Não Processado')
    table.string('nm_medico', 50)
    table.string('nm_paciente', 80)
    table.string('ds_incidente', 100).notNullable()
    table.string('ds_subtipo_incidente', 100)
    table.string('nr_atend', 10)
    table.dateTime('dt_atend')
    table.string('ds_medic', 200)
    table.string('ds_protocolo', 200)
    table.string('ds_cateter', 200)
    table.string('cd_paciente', 10)
    table.string('escala_news', 300)
    table.dateTime('dt_cadastro').defaultTo(knex.fn.now())
    table.integer('cd_escala_news')
    table.string('ds_email', 100)
  })

  await createTableIfMissing(knex, 'not_inc_pre_proc', (table) => {
    table.increments('id').primary()
    table
      .integer('id_incidente')
      .unsigned()
      .references('id')
      .inTable('not_inc_incidentes')
      .onDelete('CASCADE')
    table.text('ds_class')
    table.dateTime('dt_pre_proc')
    table.integer('cd_resp')
    table.text('ds_resp')
    table.text('ds_mot_class')
    table.text('ds_resp_proc')
  })

  await createTableIfMissing(knex, 'not_inc_pre_proc_bkp', (table) => {
    table.integer('id_incidente').notNullable()
    table.string('ds_class', 15).notNullable()
    table.dateTime('dt_pre_proc').notNullable()
    table.string('ds_resp', 60).notNullable()
    table.string('ds_mot_class', 300).notNullable()
    table.string('ds_resp_proc', 50)
  })

  await createTableIfMissing(knex, 'not_inc_pos_proc', (table) => {
    table.increments('id').primary()
    table
      .integer('id_notificacao')
      .unsigned()
      .references('id')
      .inTable('not_inc_incidentes')
      .onDelete('CASCADE')
    table.string('gravidade', 300)
    table.string('ds_gravidade', 300)
    table.string('ds_prot', 300)
    table.string('ds_e_rela', 300)
    table.string('ds_prod_rela', 300)
    table.string('nr_lote', 30)
    table.string('nr_reg_anvisa', 30)
    table.string('ds_fornecedor', 300)
    table.string('ds_opt_rela', 300)
    table.string('ds_ishi', 10)
    table.dateTime('dt_ishi')
    table.string('ds_bow', 10)
    table.dateTime('dt_bow')
    table.string('ds_naranjo', 10)
    table.dateTime('dt_naranjo')
    table.string('ds_acao_1_1', 300)
    table.string('ds_acao_1_2', 300)
    table.string('ds_acao_1_3', 300)
    table.string('ds_acao_1_4', 300)
    table.string('ds_acao_2_1', 300)
    table.string('ds_acao_2_2', 300)
    table.string('ds_acao_2_3', 300)
    table.string('ds_acao_2_4', 500)
    table.string('ds_acao_3_1', 500)
    table.string('ds_acao_3_2', 500)
    table.string('ds_acao_3_3', 500)
    table.string('ds_acao_3_4', 500)
    table.dateTime('dt_pos_proc')
    table.string('ds_just_rela', 500)
    table.string('aval_eficacia', 10)
    table.string('aval_evidencias', 500)
  })

  await createTableIfMissing(knex, 'not_inc_ishikawa', (table) => {
    table.increments('id').primary()
    table
      .integer('id_not')
      .unsigned()
      .references('id')
      .inTable('not_inc_incidentes')
      .onDelete('CASCADE')
    table.dateTime('dt_diagrama').notNullable()
    table.string('tarefa1', 100)
    table.string('tarefa2', 100)
    table.string('ambiente1', 100)
    table.string('ambiente2', 100)
    table.string('paciente1', 100)
    table.string('paciente2', 100)
    table.string('gestao1', 100)
    table.string('gestao2', 100)
    table.string('equipe1', 100)
    table.string('equipe2', 100)
    table.string('individuo1', 100)
    table.string('individuo2', 100)
    table.string('comunica', 100).notNullable()
  })

  await createTableIfMissing(knex, 'not_inc_bowtie', (table) => {
    table.increments('id').primary()
    table
      .integer('id_not')
      .unsigned()
      .references('id')
      .inTable('not_inc_incidentes')
      .onDelete('CASCADE')
    table.dateTime('dt_diagrama').notNullable()
    table.string('ameaca1', 100)
    table.string('ameaca2', 100)
    table.string('ameaca3', 100)
    table.string('ameaca4', 100)
    table.string('ameaca5', 100)
    table.string('barreira1', 100)
    table.string('barreira2', 100)
    table.string('barreira3', 100)
    table.string('evento', 100)
    table.string('mitigacao1', 100)
    table.string('mitigacao2', 100)
    table.string('mitigacao3', 100)
    table.string('dano1', 100)
    table.string('dano2', 100)
    table.string('dano3', 100)
    table.string('dano4', 100)
    table.string('dano5', 100)
  })

  await createTableIfMissing(knex, 'not_inc_naranjo', (table) => {
    table.increments('id').primary()
    table
      .integer('id_not')
      .unsigned()
      .references('id')
      .inTable('not_inc_incidentes')
      .onDelete('CASCADE')
    table.dateTime('dt_diagrama').notNullable()
    table.decimal('questao1', 10, 0)
    table.decimal('questao2', 10, 0)
    table.decimal('questao3', 10, 0)
    table.decimal('questao4', 10, 0)
    table.decimal('questao5', 10, 0)
    table.decimal('questao6', 10, 0)
    table.decimal('questao7', 10, 0)
    table.decimal('questao8', 10, 0)
    table.decimal('questao9', 10, 0)
    table.decimal('questao10', 10, 0)
    table.decimal('soma', 10, 0)
  })

  await createTableIfMissing(knex, 'not_inc_resp', (table) => {
    table.increments('id').primary()
    table.string('ds_resp', 100).notNullable()
    table.string('user_cadastro', 30).notNullable()
    table.dateTime('dt_cadastro').notNullable().defaultTo(knex.fn.now())
  })

  await createTableIfMissing(knex, 'not_inc_tipos', (table) => {
    table.increments('id').primary()
    table.boolean('ie_sub_incidente').notNullable().defaultTo(false)
    table.string('ds_tipo', 45).notNullable()
    table.boolean('ie_qualidade').notNullable().defaultTo(false)
    table.boolean('ie_pesquisa').notNullable().defaultTo(false)
    table.dateTime('dt_cadastro').notNullable().defaultTo(knex.fn.now())
    table.string('usr_cadastro', 45).notNullable()
  })

  await createTableIfMissing(knex, 'not_inc_usuarios', (table) => {
    table.increments('id').primary()
    table.string('usuario', 50).notNullable()
    table.string('senha', 50).notNullable()
  })

  await createTableIfMissing(knex, 'not_inc_perm', (table) => {
    table.increments('id').primary()
    table.integer('id_user').notNullable()
    table.boolean('pre_proc').notNullable().defaultTo(false)
    table.boolean('nuc_seg').notNullable().defaultTo(false)
    table.boolean('adm').notNullable().defaultTo(false)
    table.boolean('comissoes').notNullable().defaultTo(false)
    table.boolean('qualidade').notNullable().defaultTo(false)
    table.boolean('compras').notNullable().defaultTo(false)
    table.boolean('pesquisa').notNullable().defaultTo(false)
  })

  await createTableIfMissing(knex, 'not_inc_excluidos', (table) => {
    table.increments('id').primary()
    table.integer('id_notificacao').notNullable()
    table.dateTime('dt_exclusao').notNullable().defaultTo(knex.fn.now())
  })
}

exports.down = async (knex) => {
  await knex.schema.dropTableIfExists('not_inc_excluidos')
  await knex.schema.dropTableIfExists('not_inc_perm')
  await knex.schema.dropTableIfExists('not_inc_usuarios')
  await knex.schema.dropTableIfExists('not_inc_tipos')
  await knex.schema.dropTableIfExists('not_inc_resp')
  await knex.schema.dropTableIfExists('not_inc_naranjo')
  await knex.schema.dropTableIfExists('not_inc_bowtie')
  await knex.schema.dropTableIfExists('not_inc_ishikawa')
  await knex.schema.dropTableIfExists('not_inc_pos_proc')
  await knex.schema.dropTableIfExists('not_inc_pre_proc_bkp')
  await knex.schema.dropTableIfExists('not_inc_pre_proc')
  await knex.schema.dropTableIfExists('not_inc_incidentes')
}
