<template>
  <PageShell title="Modelos de Documentos" subtitle="PDFs privados e posicionamento dos campos de geração">
    <section class="panel"><form class="grid gap-3 md:grid-cols-4" @submit.prevent="saveTemplate"><input v-model="form.name" class="input" placeholder="Nome" required><select v-model="form.document_type" class="input" required><option value="" disabled>Tipo</option><option v-for="type in types" :key="type">{{type}}</option></select><select v-model="form.insurance_provider_id" class="input"><option value="">Genérico (todos)</option><option v-for="i in insurances" :key="i.id" :value="i.id">{{i.name}}</option></select><button class="btn">{{editing?'Salvar':'Criar modelo'}}</button></form></section>
    <section class="panel overflow-x-auto"><table class="table"><thead><tr><th>Modelo</th><th>Tipo</th><th>Convênio</th><th>Versão</th><th>Ações</th></tr></thead><tbody><tr v-for="item in templates" :key="item.id"><td>{{item.name}}<br><small>{{item.active?'Ativo':'Inativo'}}</small></td><td>{{item.document_type}}</td><td>{{item.insurance_name||'Genérico'}}</td><td>{{item.version}}</td><td class="space-x-2"><button class="link" @click="edit(item)">Configurar</button><label class="link">Enviar PDF<input class="hidden" type="file" accept="application/pdf" @change="uploadTemplate($event,item.id)"></label><button class="link" @click="toggle(item)">{{item.active?'Desativar':'Ativar'}}</button></td></tr></tbody></table></section>
    <section v-if="editing" class="panel"><h2 class="section-title">Campos do modelo</h2><p class="mb-3 text-sm text-gray-500">Coordenadas X/Y em pontos PDF, com origem no canto superior esquerdo.</p><div v-for="(field,index) in fields" :key="index" class="mb-2 grid gap-2 md:grid-cols-8"><select v-model="field.field_key" class="input md:col-span-2"><option v-for="key in keys" :key="key">{{key}}</option></select><input v-model.number="field.page" class="input" type="number" min="1" placeholder="Página"><input v-model.number="field.x" class="input" type="number" placeholder="X"><input v-model.number="field.y" class="input" type="number" placeholder="Y"><input v-model.number="field.font_size" class="input" type="number" placeholder="Fonte"><input v-model.number="field.width" class="input" type="number" placeholder="Largura"><button class="link" @click="fields.splice(index,1)">Remover</button></div><div class="flex gap-3"><button class="btn" @click="addField">Adicionar campo</button><button class="btn" @click="saveFields">Salvar campos</button></div></section>
  </PageShell>
</template>
<script setup lang="ts">/* eslint-disable @typescript-eslint/no-explicit-any */
import{onMounted,reactive,ref}from'vue';import api from '@/plugins/axios';import PageShell from '@/components/PageShell.vue';
const types=['CONSULTATION_GUIDE','PHYSIOTHERAPY_GUIDE','ELECTROSTIMULATION','OTHER'],keys=['PATIENT_NAME','PATIENT_CARD_NUMBER','PATIENT_BIRTH_DATE','INSURANCE_ANS_REGISTRATION','DOCTOR_NAME','DOCTOR_COUNCIL','DOCTOR_COUNCIL_NUMBER','DOCTOR_STATE','DOCTOR_CBO','REQUEST_DATE','PROCEDURE_CODE','PROCEDURE_DESCRIPTION','REQUESTED_QUANTITY','DOCTOR_SIGNATURE','INSURANCE_LOGO'];const templates=ref<any[]>([]),insurances=ref<any[]>([]),editing=ref<number|null>(null),fields=ref<any[]>([]),form=reactive<any>({name:'',document_type:'',insurance_provider_id:''});async function load(){[templates.value,insurances.value]=await Promise.all([(await api.get('/document-templates')).data,(await api.get('/insurance-providers')).data])}async function saveTemplate(){if(editing.value)await api.put(`/document-templates/${editing.value}`,form);else await api.post('/document-templates',form);editing.value=null;Object.assign(form,{name:'',document_type:'',insurance_provider_id:''});await load()}async function edit(item:any){const detail=(await api.get(`/document-templates/${item.id}`)).data;editing.value=item.id;Object.assign(form,detail);fields.value=detail.fields}function addField(){fields.value.push({field_key:'PATIENT_NAME',page:1,x:0,y:0,font_size:10})}async function saveFields(){await api.put(`/document-templates/${editing.value}/fields`,{fields:fields.value})}async function uploadTemplate(event:Event,id:number){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;await api.post(`/document-templates/${id}/file`,file,{headers:{'Content-Type':'application/pdf','X-File-Name':encodeURIComponent(file.name)}});await load()}async function toggle(item:any){await api.put(`/document-templates/${item.id}`,{active:!item.active});await load()}onMounted(load)
</script>
